import { ILocationInfo } from "../../Interfaces";

export const mockLocationData: ILocationInfo[] = [
  {
    id: "1",
    name: "Central Parking",
    address: "123 Main St, Cityville",
    noOfSlotsAvailable: 15,
    latitude: "40.7128",
    longitude: "-74.0060",
  },
  {
    id: "2",
    name: "West Side Parking",
    address:
      "896 main st,Cityville ,uppar kot ,bulandshahr, up , indian, mock address to show truncated address and tooltip",
    noOfSlotsAvailable: 5,
    latitude: "34.0522",
    longitude: "-118.2437",
  },
  {
    id: "3",
    name: "East End Parking",
    address: "789 Oak St, Villagetown",
    noOfSlotsAvailable: 20,
    latitude: "51.5074",
    longitude: "-0.1278",
  },
  {
    id: "4",
    name: "North Parking",
    address: "101 Pine St, Metropolis",
    noOfSlotsAvailable: 0,
    latitude: "35.6895",
    longitude: "139.6917",
  },
  {
    id: "5",
    name: "South Parking",
    address: "202 Cedar St, Hamlet",
    noOfSlotsAvailable: 10,
    latitude: "48.8566",
    longitude: "2.3522",
  },
  {
    id: "1",
    name: "Central Parking",
    address: "123 Main St, Cityville",
    noOfSlotsAvailable: 15,
    latitude: "40.7128",
    longitude: "-74.0060",
  },
  {
    id: "2",
    name: "West Side Parking",
    address: "456 Elm St, Townsville",
    noOfSlotsAvailable: 5,
    latitude: "34.0522",
    longitude: "-118.2437",
  },
  {
    id: "3",
    name: "East End Parking",
    address: "789 Oak St, Villagetown",
    noOfSlotsAvailable: 20,
    latitude: "51.5074",
    longitude: "-0.1278",
  },
  {
    id: "4",
    name: "North Parking",
    address: "101 Pine St, Metropolis",
    noOfSlotsAvailable: 7,
    latitude: "35.6895",
    longitude: "139.6917",
  },
  {
    id: "5",
    name: "South Parking",
    address: "202 Cedar St, Hamlet",
    noOfSlotsAvailable: 10,
    latitude: "48.8566",
    longitude: "2.3522",
  },
];
